name: Echo Name Workflow

on: 
  push:
    branches:
      - main

jobs:
  echo_name_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Echo my name
      run: echo "Bahar"
